[package]
name = "picofb"
version = "0.0.0"
edition = "2021"

[lib]
path = "lib.rs"

[[example]]
name = "example"
path = "example.rs"

[[example]]
name = "pause"
path = "pause.rs"

[dependencies]
sdl2-sys = "0.36.0"
